name: Publish To PyPi

on:
  push:
    branches:
      - dev
    tags:
      - '*.*.*'
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Check Version
        id: check-version
        run: |
          version=$(grep -Po '^version\s*=\s*"\K[^"]+' pyproject.toml | head -n 1)
          if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version=$version" >> $GITHUB_ENV
          else
            echo "Not a valid version bump. Skipping tag creation."
            exit 0
          fi

      - name: Check if Tag Exists
        id: tag_exists
        run: |
          if git rev-parse "refs/tags/${{ env.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.version }} already exists."
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && env.tag_exists == 'false' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Checkout Tag
        if: ${{ github.ref == 'refs/heads/dev' && env.version != '' }}
        run: |
          git fetch --tags
          git checkout "refs/tags/${{ env.version }}"
          echo "Checked out tag ${{ env.version }}"

      - name: Build project for distribution
        run: uv build

      - name: Publish to PyPI
        run: uv publish
